@startuml

participant "lightController : TrafficLightController" as TrafficLightController
participant "carController1 : CarController" as CarController1
participant "carController2 : CarController2" as CarController2
participant "car : Car" as Car
participant "trafficLight : TrafficLight" as TrafficLight

box "Thread TrafficLightController"
    loop Every 5 seconds
        TrafficLightController -> TrafficLight: setGreen()
        activate TrafficLight
        deactivate TrafficLight
    end
end box

box "Thread CarController"
    loop Every 1 second
        CarController1 -> Car: move()
        activate Car
        Car -> TrafficLight: isGreen()
        activate TrafficLight
        alt if isGreen() == true or car hasCrossedLight
            Car -> Car: continue moving
        else
            Car -> Car: stop
        end
        deactivate TrafficLight
        deactivate Car
    end
end box

box "Thread CarController2"
    loop Every 1 second
        CarController2 -> Car: move()
        activate Car
        Car -> TrafficLight: isGreen()
        activate TrafficLight
        alt if isGreen() == true or car hasCrossedLight
            Car -> Car: continue moving
        else
            Car -> Car: stop
        end
        deactivate TrafficLight
        deactivate Car
    end
end box

@enduml

