@startuml

participant "lightController : TrafficLightController" as TrafficLightController
participant "carController1 : CarController" as CarController1
participant "carController2 : CarController2" as CarController2
participant "car : Car" as Car
participant "trafficLight : TrafficLight" as TrafficLight

note over CarController1, CarController2: Les deux CarControllers fonctionnent en parallèle

box "Thread TrafficLightController"
    loop Every 5 seconds
        TrafficLightController -> TrafficLight: setGreen()
        activate TrafficLight
        deactivate TrafficLight
    end
end box

box "Threads CarController1 et CarController2"
    loop Every 100 milliseconds
        CarController1 -> Car: move()
        activate Car
        Car -> TrafficLight: isGreen()
        activate TrafficLight
        alt if isGreen() or car hasCrossedLight
            Car -> Car: continue moving
        else
            Car -> Car: stop
        end
        deactivate TrafficLight
        deactivate Car

        CarController2 -> Car: move()
        activate Car
        Car -> TrafficLight: isGreen()
        activate TrafficLight
        alt if isGreen() or car hasCrossedLight
            Car -> Car: continue moving
        else
            Car -> Car: stop
        end
        deactivate TrafficLight
        deactivate Car
    end
end box

@enduml
